Write-Host "test 1"
./aisd_lb3 -f tests/test1.txt
Write-Host "test 2"
./aisd_lb3  -f tests/test2.txt
Write-Host "test 3"
./aisd_lb3  -f tests/test3.txt
Write-Host "test 4"
./aisd_lb3  -f tests/test4.txt
Write-Host "test 5"
./aisd_lb3  -f tests/test5.txt
Write-Host "test 6"
./aisd_lb3  -f tests/test6.txt
Write-Host "test 7"
./aisd_lb3  -f tests/test7.txt
Write-Host "test 8"
./aisd_lb3 -f tests/test8.txt
Write-Host "test 9"
./aisd_lb3 -f tests/test9.txt
Write-Host "test 10"
./aisd_lb3 -f tests/test10.txt
Write-Host "test 11"
./aisd_lb3 -f tests/test11.txt
Write-Host "test 12"
./aisd_lb3 -f tests/test12.txt

